export const ACTIONS = {
   GET_ALL_USERS: "GET_ALL_USERS",
   GET_ALL_USERS_REQUEST_SUCCESS: "GET_USERS_REQUEST_SUCCESS",
   REGISTRATION: "REGISTRATION",
   SEND_DATA: "SEND_DATA",
   LOGIN: "LOGIN",
   SEND_ITEM: "SEND_ITEM",
   GET_USER_DATA: "GET_USER_DATA",
   CREATE_COLLECTION: "CREATE_COLLECTION",
   GET_DATA_OF_NEW_USER: "GET_DATA_OF_NEW_USER",
   GET_USER: "GET_USER",
   GET_USER_REQUEST_SUCCESS:"GET_USER_REQUEST_SUCCESS",
   LOGOUT: "LOGOUT",
   GET_COLLECTION_DATA:"GET_COLLECTION_DATA",
   CREATE_ITEM:"CREATE_ITEM",
   DELETE_ITEM: "DELETE_ITEM"
}